.TH m6 1 "03-jan-2013" "version 6.0" "USER COMMANDS"
.SH NAME
6 \- A tool to build and manipulate a MRS 6 server and its data files
.SH SYNOPSIS
.TP
\fBm6\fP \fIcommand\fP [\fIoptions\fP] [\fIargs\fP]
.SH OVERVIEW
MRS is a full text indexing toolkit. It is used to index large, text based
databanks containing biological or medical information.

Run `m6 help` to access the built-in tool documentation.
.SH FILES
.TP
.B __CONFIG_DIR__/m6-config.xml
This file contains all the configuration details.
.TP
.B __SCRIPT_DIR__
The directory containing the parser scripts for mrs.
.SH AUTHOR
Maarten L. Hekkelman (m.hekkelman (at) cmbi.ru.nl)
.SH SEE ALSO
mrs-build(1), mrs-query(1), mrs-config.xml(5)
